spring.application.name=music_learner
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/music_learner?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.username=music_learner_user
spring.datasource.password=root_password
app.name=MusicLearning
app.version=1.0.0